// <auto-generated />
using DemoWebAPIforstd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoWebAPIforstd.Migrations
{
    [DbContext(typeof(EnrollDbContextcs))]
    [Migration("20221116232457_AllProject")]
    partial class AllProject
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DemoWebAPIforstd.Models.Enroll", b =>
                {
                    b.Property<int>("enid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("enid"), 1L, 1);

                    b.Property<string>("studentid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subjectid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("enid");

                    b.ToTable("enrolls");
                });

            modelBuilder.Entity("DemoWebAPIforstd.Models.Student", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("GPA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stuaddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stuid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stuimg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stulastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stuname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stuphone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("students");
                });

            modelBuilder.Entity("DemoWebAPIforstd.Models.Subjects", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("subid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
